import { expect, test } from "@playwright/test";

import { dismissOnboarding, gotoEditor, openPanel, seedSession, setPhrase, waitForStage } from "./helpers";

/**
 * The export surface, driven through the dialog rather than the module.
 *
 * `check-exports.ts` already proves every generated document parses. What only
 * a browser can prove is that the buttons produce a file at all, that the two
 * file formats stay distinct at the UI boundary, and that opening a project
 * really does restore the document.
 */

test.beforeEach(async ({ page }) => {
  await dismissOnboarding(page);
});

const openExport = async (page: import("@playwright/test").Page) => {
  await page.getByRole("button", { name: "Export", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
};

test("the standalone page downloads and declares what it needs", async ({ page }) => {
  await gotoEditor(page);
  await setPhrase(page, "EXPORT ME");
  await openExport(page);

  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: /Standalone page/ }).click();
  const file = await download;

  expect(file.suggestedFilename()).toMatch(/\.html$/);

  const stream = await file.createReadStream();
  const html = await new Promise<string>((resolve, reject) => {
    const chunks: Buffer[] = [];
    stream.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    stream.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    stream.on("error", reject);
  });

  expect(html).toContain("EXPORT ME");
  expect(html).toContain("Generated by Titlecard");
  // "Standalone" means one file, not offline, and the file has to say so.
  expect(html).toContain("NEEDS THE NETWORK");
  expect(html).toContain("<style>");
  expect(html).toContain("gsap.timeline");
});

test("a project file and a look are different documents", async ({ page }) => {
  await gotoEditor(page);
  await setPhrase(page, "SECRET WORDS");
  await openPanel(page, "Presets");

  const read = async (trigger: Promise<unknown>) => {
    const download = page.waitForEvent("download");
    await trigger;
    const file = await download;
    const stream = await file.createReadStream();
    const body = await new Promise<string>((resolve, reject) => {
      const chunks: Buffer[] = [];
      stream.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
      stream.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
      stream.on("error", reject);
    });
    return { name: file.suggestedFilename(), body };
  };

  const project = await read(page.getByRole("button", { name: "Save project" }).click());
  expect(project.name).toMatch(/\.titlecard\.json$/);
  expect(project.body).toContain("SECRET WORDS");

  const look = await read(page.getByRole("button", { name: "Export this look" }).click());
  expect(look.name).toMatch(/\.titlecard-look\.json$/);
  // The whole point of the split: a look cannot carry someone's words.
  expect(look.body).not.toContain("SECRET WORDS");
  expect(JSON.parse(look.body).layers).toBeUndefined();
});

test("opening a project file restores the whole document", async ({ page }) => {
  await seedSession(page, {
    schemaVersion: 3,
    name: "Seeded",
    layers: [{ text: "BEFORE", templateId: "fade-up", visible: true, name: "Headline" }],
  });
  await gotoEditor(page);
  await waitForStage(page);
  await openPanel(page, "Presets");

  const projectFile = JSON.stringify({
    $schema: "titlecard/project@3",
    schemaVersion: 3,
    name: "Imported scene",
    canvas: { formatId: "instagram-square", width: 1080, height: 1080, safeZones: false },
    layers: [
      { name: "One", text: "IMPORTED ONE", templateId: "film-title", visible: true },
      { name: "Two", text: "IMPORTED TWO", templateId: "punch-words", visible: true, delay: 0.6 },
    ],
    activeLayerIndex: 1,
  });

  // Opening a project replaces the canvas, so it asks first.
  page.once("dialog", (dialog) => dialog.accept());
  await page.setInputFiles('input[type="file"][accept*="json"]', {
    name: "scene.titlecard.json",
    mimeType: "application/json",
    buffer: Buffer.from(projectFile, "utf8"),
  });

  await expect(page.locator(".stw-preview [data-stw-layer]")).toHaveCount(2);
  await expect(page.locator(".stw-preview .stw-sr").first()).toHaveText("IMPORTED ONE");

  const box = (await page.locator(".stw-preview .stw-canvas").boundingBox())!;
  expect(box.width / box.height).toBeCloseTo(1, 1);
});

test("declining the confirmation keeps the current project", async ({ page }) => {
  await gotoEditor(page);
  await setPhrase(page, "KEEP ME");
  await openPanel(page, "Presets");

  page.once("dialog", (dialog) => dialog.dismiss());
  await page.setInputFiles('input[type="file"][accept*="json"]', {
    name: "other.titlecard.json",
    mimeType: "application/json",
    buffer: Buffer.from(
      JSON.stringify({
        schemaVersion: 3,
        name: "Other",
        layers: [{ text: "REPLACED", templateId: "fade-up", visible: true }],
      }),
      "utf8",
    ),
  });

  await expect(page.locator(".stw-preview .stw-sr").first()).toHaveText("KEEP ME");
});

test("a version 1 preset still opens", async ({ page }) => {
  await gotoEditor(page);
  await openPanel(page, "Presets");

  page.once("dialog", (dialog) => dialog.accept());
  await page.setInputFiles('input[type="file"][accept*="json"]', {
    name: "legacy.json",
    mimeType: "application/json",
    buffer: Buffer.from(
      JSON.stringify({
        $schema: "semantic-text-animator/preset@1",
        phrase: "Agent 3",
        template: "agent-reveal",
        palette: "terminal",
        glyphPool: "binary",
        motion: { speed: 1.4, stagger: 0.02, loop: false },
        type: { fontSize: 9, tracking: 0.1, leading: 1.4, weight: 700 },
        canvas: "dark",
      }),
      "utf8",
    ),
  });

  await expect(page.locator(".stw-preview .stw-sr").first()).toHaveText("Agent 3");
});

test("a PNG sequence too large to deliver is refused before it starts", async ({ page }) => {
  await gotoEditor(page);
  await openExport(page);

  await page.getByRole("tab", { name: "Frames" }).click();

  const set = async (id: string, value: string) => {
    await page.locator(`#${id}`).fill(value);
    await page.locator(`#${id}`).press("Enter");
  };
  await set("frames-width", "3840");
  await set("frames-height", "2160");
  await set("frames-fps", "60");
  await set("frames-duration", "30");

  // A frame cap bounds nothing on its own; the budget is in bytes.
  await expect(page.getByText(/Too large/)).toBeVisible();
  await expect(page.getByRole("button", { name: /Export \d+ PNGs/ })).toBeDisabled();

  await set("frames-width", "640");
  await set("frames-height", "360");
  await set("frames-duration", "1");
  await expect(page.getByRole("button", { name: /Export \d+ PNGs/ })).toBeEnabled();
});
